"""Initial models - Biography, Chapter, Source, GenerationJob

Revision ID: 176a9cbacdac
Revises: 
Create Date: 2025-10-07 12:20:22.583744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176a9cbacdac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biographies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bio_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_biography_character_status', 'biographies', ['character_name', 'status'], unique=False)
    op.create_index('idx_biography_status_created', 'biographies', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_biographies_character_name'), 'biographies', ['character_name'], unique=False)
    op.create_index(op.f('ix_biographies_id'), 'biographies', ['id'], unique=False)
    op.create_index(op.f('ix_biographies_status'), 'biographies', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('publication_date', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_created', 'sources', ['created_at'], unique=False)
    op.create_index('idx_source_validation_relevance', 'sources', ['validation_status', 'relevance_score'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=False)
    op.create_index(op.f('ix_sources_validation_status'), 'sources', ['validation_status'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biography_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['biography_id'], ['biographies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_biography_number', 'chapters', ['biography_id', 'number'], unique=True)
    op.create_index(op.f('ix_chapters_biography_id'), 'chapters', ['biography_id'], unique=False)
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biography_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['biography_id'], ['biographies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_biography_status', 'generation_jobs', ['biography_id', 'status'], unique=False)
    op.create_index('idx_job_status_created', 'generation_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_generation_jobs_biography_id'), 'generation_jobs', ['biography_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_biography_id'), table_name='generation_jobs')
    op.drop_index('idx_job_status_created', table_name='generation_jobs')
    op.drop_index('idx_job_biography_status', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_biography_id'), table_name='chapters')
    op.drop_index('idx_chapter_biography_number', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_sources_validation_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index('idx_source_validation_relevance', table_name='sources')
    op.drop_index('idx_source_created', table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_biographies_status'), table_name='biographies')
    op.drop_index(op.f('ix_biographies_id'), table_name='biographies')
    op.drop_index(op.f('ix_biographies_character_name'), table_name='biographies')
    op.drop_index('idx_biography_status_created', table_name='biographies')
    op.drop_index('idx_biography_character_status', table_name='biographies')
    op.drop_table('biographies')
    # ### end Alembic commands ###
