# Alertmanager Configuration for BookGen
global:
  resolve_timeout: 5m
  # Slack webhook URL (configure via environment variable)
  slack_api_url: "${SLACK_WEBHOOK_URL}"

# Route configuration
route:
  # Default receiver
  receiver: 'default'
  
  # Group alerts by alertname and component
  group_by: ['alertname', 'component']
  
  # How long to wait before sending a notification about new alerts
  group_wait: 10s
  
  # How long to wait before sending notification about new alerts in a group
  group_interval: 10s
  
  # How long to wait before sending a notification again
  repeat_interval: 3h
  
  # Child routes
  routes:
    # Critical alerts - send immediately
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h
    
    # Warning alerts - less urgent
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 6h

# Receivers configuration
receivers:
  # Default receiver (can be configured for email)
  - name: 'default'
    # Email configuration (optional, configure SMTP settings)
    # email_configs:
    #   - to: 'admin@example.com'
    #     from: 'alertmanager@bookgen.com'
    #     smarthost: 'smtp.gmail.com:587'
    #     auth_username: 'your-email@gmail.com'
    #     auth_password: '${SMTP_PASSWORD}'
    #     headers:
    #       Subject: '[BookGen] Alert: {{ .GroupLabels.alertname }}'

  # Critical alerts receiver
  - name: 'critical-alerts'
    slack_configs:
      - channel: '#bookgen-alerts'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          *Summary:* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          *Description:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          *Component:* {{ .GroupLabels.component }}
          *Severity:* {{ .GroupLabels.severity }}
        send_resolved: true
        color: 'danger'
    
    # Email for critical alerts (optional)
    # email_configs:
    #   - to: 'admin@example.com,oncall@example.com'
    #     from: 'alertmanager@bookgen.com'
    #     headers:
    #       Subject: '🚨 [BookGen CRITICAL] {{ .GroupLabels.alertname }}'

  # Warning alerts receiver
  - name: 'warning-alerts'
    slack_configs:
      - channel: '#bookgen-alerts'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: |
          *Summary:* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          *Description:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          *Component:* {{ .GroupLabels.component }}
        send_resolved: true
        color: 'warning'

# Inhibition rules - prevent notifications for certain alerts when others are firing
inhibit_rules:
  # Inhibit warning if critical is firing for the same component
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['component']
  
  # Inhibit high memory alert if critical memory is firing
  - source_match:
      alertname: 'CriticalMemoryUsage'
    target_match:
      alertname: 'HighMemoryUsage'
  
  # Inhibit high disk alert if critical disk is firing
  - source_match:
      alertname: 'CriticalDiskUsage'
    target_match:
      alertname: 'HighDiskUsage'
